# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hssh < Formula
  desc "A CLI to easily sync, list, search and connect to SSH hosts"
  homepage ""
  version "1.0.0"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/heply/hssh/releases/download/1.0.0/hssh_1.0.0_darwin_amd64.tar.gz"
    sha256 "c86d67e588c673cdff6f106dde962dfeef7cb08bff305bd8ec5f3cc2da7ad897"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/heply/hssh/releases/download/1.0.0/hssh_1.0.0_darwin_arm64.tar.gz"
    sha256 "382a234873bc20048a64761e0390d64fa77aff8ef329e1663db5c86d8929132e"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/heply/hssh/releases/download/1.0.0/hssh_1.0.0_linux_amd64.tar.gz"
    sha256 "5367af35b9226194c1337b097493562685fd50c10b1bbb4014700b006c874334"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/heply/hssh/releases/download/1.0.0/hssh_1.0.0_linux_arm64.tar.gz"
    sha256 "9f3c1e52421135928f9fe95015a92f27e0fd1bc6dd79344281b8a900371b03c3"
  end

  depends_on "fzf"

  def install
    bin.install "hssh"
  end
end
