# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hssh < Formula
  desc "A CLI to easily sync, list, search and connect to SSH hosts"
  homepage ""
  version "1.3.0"
  license "MIT"

  depends_on "fzf"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/beliven-it/hssh/releases/download/1.3.0/hssh_1.3.0_darwin_arm64.tar.gz"
      sha256 "1887b199f8b1c916758418d41c07bca9231fa4e02b3dab6d969e1be8554801aa"

      def install
        bin.install "hssh"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/beliven-it/hssh/releases/download/1.3.0/hssh_1.3.0_darwin_amd64.tar.gz"
      sha256 "43e613d87c35ad64aed5ddf965ca53c90a374fe9ba5864b22e10a044517fa30e"

      def install
        bin.install "hssh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/beliven-it/hssh/releases/download/1.3.0/hssh_1.3.0_linux_amd64.tar.gz"
      sha256 "e40b9f46754eb5af71644fe0873976ff264f72e820b42cf76b368e66f8a59762"

      def install
        bin.install "hssh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/beliven-it/hssh/releases/download/1.3.0/hssh_1.3.0_linux_arm64.tar.gz"
      sha256 "2f3655040b343419169aab0151f7bb0e3984f6556873874acd8fa36e289e2706"

      def install
        bin.install "hssh"
      end
    end
  end

  def caveats
    <<~EOS
      Run `hssh init` to generate config file inside
       `~/.config/hssh/config.yml` (works only if not exists yet)
       or let the CLI creating it automatically on first run (every command).

       Type `hssh help` for further information.
    EOS
  end
end
