# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HsshAT121 < Formula
  desc "A CLI to easily sync, list, search and connect to SSH hosts"
  homepage ""
  version "1.2.1"
  license "MIT"

  depends_on "fzf"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/beliven-it/hssh/releases/download/1.2.1/hssh_1.2.1_darwin_amd64.tar.gz"
      sha256 "ba1d9e1c633afb821768d01185613c9a80a7d4e3bb4be5c41c829a0d2cb0ede8"

      def install
        bin.install "hssh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/beliven-it/hssh/releases/download/1.2.1/hssh_1.2.1_darwin_arm64.tar.gz"
      sha256 "ed5037cf1a596a558997f4529aaa66c42430f75345fd18e4106f8564f67a253e"

      def install
        bin.install "hssh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/beliven-it/hssh/releases/download/1.2.1/hssh_1.2.1_linux_arm64.tar.gz"
      sha256 "57e5829a82aeb116e8bbdd1e477d0759ec0f701a23a924651da71d94eff3c846"

      def install
        bin.install "hssh"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/beliven-it/hssh/releases/download/1.2.1/hssh_1.2.1_linux_amd64.tar.gz"
      sha256 "adbdd5a48f17f36f7fe876cd6799fb982768d49b1a37316d95ce264e7d9d3d33"

      def install
        bin.install "hssh"
      end
    end
  end

  def caveats
    <<~EOS
      Run `hssh init` to generate config file inside
       `~/.config/hssh/config.yml` (works only if not exists yet)
       or let the CLI creating it automatically on first run (every command).

       Type `hssh help` for further information.
    EOS
  end
end
