# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OpsiAT121 < Formula
  desc "All-in-one CLI for Beliven Ops daily usage!"
  homepage ""
  version "1.2.1"
  license "MIT"

  depends_on "1password/tap/1password-cli"
  depends_on "beliven-it/tap/hssh"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/beliven-it/opsi/releases/download/1.2.1/opsi_1.2.1_darwin_arm64.tar.gz"
      sha256 "dc2b94d4ea7c14b28a0ca6b74a3baebb3d9ea74e04994e62bc651228f982c667"

      def install
        bin.install "opsi"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/beliven-it/opsi/releases/download/1.2.1/opsi_1.2.1_darwin_amd64.tar.gz"
      sha256 "14799801678feccd68713a23168008b00034d5fa0422f74b3228983cb1529e8f"

      def install
        bin.install "opsi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/beliven-it/opsi/releases/download/1.2.1/opsi_1.2.1_linux_amd64.tar.gz"
      sha256 "2c942c655bd3d3b4668bc1522b1021db7b404f06602e0f94de82c199c8d99589"

      def install
        bin.install "opsi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/beliven-it/opsi/releases/download/1.2.1/opsi_1.2.1_linux_arm64.tar.gz"
      sha256 "18a124858befffbb46767a84cf1642d799b9d28b0ce5d818e7050375cac4e971"

      def install
        bin.install "opsi"
      end
    end
  end

  def caveats
    <<~EOS
      Run `opsi init` to generate config file inside
       `~/.config/opsi/config.yml` (works only if not exists yet).

       Type `opsi help` for further information.
    EOS
  end
end
