# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OpsiAT120 < Formula
  desc "All-in-one CLI for Beliven Ops daily usage!"
  homepage ""
  version "1.2.0"
  license "MIT"

  depends_on "fzf"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/beliven-it/opsi/releases/download/1.2.0/opsi_1.2.0_darwin_amd64.tar.gz"
      sha256 "c928a9a2c7fd925f1ea4536fb138c340b7a96f67c10a087f80fb2379b429197e"

      def install
        bin.install "opsi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/beliven-it/opsi/releases/download/1.2.0/opsi_1.2.0_darwin_arm64.tar.gz"
      sha256 "1febc255d1a75716ebce6370582bdc86f8e9fe947bf89ac56b856471fa90d37c"

      def install
        bin.install "opsi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/beliven-it/opsi/releases/download/1.2.0/opsi_1.2.0_linux_arm64.tar.gz"
      sha256 "5f263fdc005e8da6272ea9131f7318729b8ebdd027ded02e56d5a69247406256"

      def install
        bin.install "opsi"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/beliven-it/opsi/releases/download/1.2.0/opsi_1.2.0_linux_amd64.tar.gz"
      sha256 "c579b443a6f1e2ceb0aa78c445378d10559b3f375ca5e38cc267984f21e53d51"

      def install
        bin.install "opsi"
      end
    end
  end

  def caveats
    <<~EOS
      Run `opsi init` to generate config file inside
       `~/.config/opsi/config.yml` (works only if not exists yet).

       Type `opsi help` for further information.
    EOS
  end
end
