# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OpsiAT1140 < Formula
  desc "All-in-one CLI for Beliven Ops daily usage!"
  homepage ""
  version "1.14.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/beliven-it/opsi/releases/download/1.14.0/opsi_1.14.0_darwin_amd64.tar.gz"
      sha256 "aea61e5562270393fa0c16e2fa852bc2023e4112cdd5446daa97ac5686d67381"

      define_method(:install) do
        bin.install "opsi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/beliven-it/opsi/releases/download/1.14.0/opsi_1.14.0_darwin_arm64.tar.gz"
      sha256 "53e9ef558112575368cdbd4335c8a5dc8fac051d12c15543213f2eea858854ec"

      define_method(:install) do
        bin.install "opsi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/beliven-it/opsi/releases/download/1.14.0/opsi_1.14.0_linux_amd64.tar.gz"
      sha256 "4fc39ce9f9a86ddcc6a427e3a5f5af78327cef0146f28943292ea6d07ad036f7"
      define_method(:install) do
        bin.install "opsi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/beliven-it/opsi/releases/download/1.14.0/opsi_1.14.0_linux_arm64.tar.gz"
      sha256 "1b260716a469fe0815fc198fce4e962d4bfda3d345b528046ac67886b995c351"
      define_method(:install) do
        bin.install "opsi"
      end
    end
  end

  def caveats
    <<~EOS
      Run `opsi init` to generate config file inside
       `~/.config/opsi/config.yml` (works only if not exists yet).

       Type `opsi help` for further information.
    EOS
  end
end
