# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OpsiAT1110 < Formula
  desc "All-in-one CLI for Beliven Ops daily usage!"
  homepage ""
  version "1.11.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/beliven-it/opsi/releases/download/1.11.0/opsi_1.11.0_darwin_amd64.tar.gz"
      sha256 "8229b17a1db8e62910d137e682a21e70b5c7c2f9e2f4962ab5b88c62805d323a"

      def install
        bin.install "opsi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/beliven-it/opsi/releases/download/1.11.0/opsi_1.11.0_darwin_arm64.tar.gz"
      sha256 "5d0eef874f7c13adcd6b179ccf2a957debfc8d1a8615c2169e41dad24ff38135"

      def install
        bin.install "opsi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/beliven-it/opsi/releases/download/1.11.0/opsi_1.11.0_linux_amd64.tar.gz"
      sha256 "ff858fe62d429cfdb0a51fbbc9b611d7b94921d0115c615c9dd5cdbce2916ee8"

      def install
        bin.install "opsi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/beliven-it/opsi/releases/download/1.11.0/opsi_1.11.0_linux_arm64.tar.gz"
      sha256 "a16b70b9548fd66b65d8a6948cf55db5cb47d841a62f6208871b3ca93444b61c"

      def install
        bin.install "opsi"
      end
    end
  end

  def caveats
    <<~EOS
      Run `opsi init` to generate config file inside
       `~/.config/opsi/config.yml` (works only if not exists yet).

       Type `opsi help` for further information.
    EOS
  end
end
