# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OpsiAT210 < Formula
  desc "All-in-one CLI for Beliven Ops daily usage!"
  homepage ""
  version "2.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/beliven-it/opsi/releases/download/2.1.0/opsi_2.1.0_darwin_amd64.tar.gz"
      sha256 "d4d93f7ada7f62205d00b2426980d2c0726f982f4aa6ea30a6a146a9aa4af28f"

      define_method(:install) do
        bin.install "opsi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/beliven-it/opsi/releases/download/2.1.0/opsi_2.1.0_darwin_arm64.tar.gz"
      sha256 "6bfb10fe181e618d3da3fa96126290daf7c2ec58661948c239856a779dcba6f4"

      define_method(:install) do
        bin.install "opsi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/beliven-it/opsi/releases/download/2.1.0/opsi_2.1.0_linux_amd64.tar.gz"
      sha256 "45186a869e98ac5719508a7549b6dcffe9e7e6d35561c2377f4282fc094081e8"
      define_method(:install) do
        bin.install "opsi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/beliven-it/opsi/releases/download/2.1.0/opsi_2.1.0_linux_arm64.tar.gz"
      sha256 "db0c4725a69ee28dca7fef0c45c085b5a1aa50976d3849c74ee1afee22cfac8f"
      define_method(:install) do
        bin.install "opsi"
      end
    end
  end

  def caveats
    <<~EOS
      Run `opsi init` to generate config file inside
       `~/.config/opsi/config.yml` (works only if not exists yet).

       Type `opsi help` for further information.
    EOS
  end
end
