# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OpsiAT170 < Formula
  desc "All-in-one CLI for Beliven Ops daily usage!"
  homepage ""
  version "1.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/beliven-it/opsi/releases/download/1.7.0/opsi_1.7.0_darwin_arm64.tar.gz"
      sha256 "b2371cf98ec7ef5efb76f49bd81278c90b460cc6b6bbf8ff7d31dac64e2700ec"

      def install
        bin.install "opsi"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/beliven-it/opsi/releases/download/1.7.0/opsi_1.7.0_darwin_amd64.tar.gz"
      sha256 "0f16a3c4046854b94549ed25fb4df451be15cd710713868cb34e8c8ccb3627e9"

      def install
        bin.install "opsi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/beliven-it/opsi/releases/download/1.7.0/opsi_1.7.0_linux_amd64.tar.gz"
      sha256 "6385a29dcf05ab69906ea2e85c0439f3aa0cd52a8a22b97bcea8793639e65dc8"

      def install
        bin.install "opsi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/beliven-it/opsi/releases/download/1.7.0/opsi_1.7.0_linux_arm64.tar.gz"
      sha256 "32cddb7eae1fde3f0abecccb9632ca49d33356dc678c3b8d2f94f15bafc01c66"

      def install
        bin.install "opsi"
      end
    end
  end

  def caveats
    <<~EOS
      Run `opsi init` to generate config file inside
       `~/.config/opsi/config.yml` (works only if not exists yet).

       Type `opsi help` for further information.
    EOS
  end
end
