# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Opsi < Formula
  desc "All-in-one CLI for Beliven Ops daily usage!"
  homepage ""
  version "1.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/beliven-it/opsi/releases/download/1.9.0/opsi_1.9.0_darwin_arm64.tar.gz"
      sha256 "0f71b31acfed2883e42feb877d0ef622895b85c465e14883f3ef76beddbca851"

      def install
        bin.install "opsi"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/beliven-it/opsi/releases/download/1.9.0/opsi_1.9.0_darwin_amd64.tar.gz"
      sha256 "73db755d26280cce9446a55a32ba3dccc523b7113bce929d7308b247f8707fc1"

      def install
        bin.install "opsi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/beliven-it/opsi/releases/download/1.9.0/opsi_1.9.0_linux_amd64.tar.gz"
      sha256 "2e6abadc0fcb71cfd496d21de2f7751ddac2b574d1b62f2280046f87907f211e"

      def install
        bin.install "opsi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/beliven-it/opsi/releases/download/1.9.0/opsi_1.9.0_linux_arm64.tar.gz"
      sha256 "63d469ff2d10cc77697a79c1809325adaa44df433121b57751f655bc93d90990"

      def install
        bin.install "opsi"
      end
    end
  end

  def caveats
    <<~EOS
      Run `opsi init` to generate config file inside
       `~/.config/opsi/config.yml` (works only if not exists yet).

       Type `opsi help` for further information.
    EOS
  end
end
