# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Opsi < Formula
  desc "All-in-one CLI for Beliven Ops daily usage!"
  homepage ""
  version "1.13.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/beliven-it/opsi/releases/download/1.13.1/opsi_1.13.1_darwin_amd64.tar.gz"
      sha256 "6f7d60357b6adb313ca2d258553de59ea57703c14fcff305de5e22615feb047e"

      def install
        bin.install "opsi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/beliven-it/opsi/releases/download/1.13.1/opsi_1.13.1_darwin_arm64.tar.gz"
      sha256 "19792d3c94baeb219cb3003b65511a4f526966eda29441c4982dbb07c4e449a2"

      def install
        bin.install "opsi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/beliven-it/opsi/releases/download/1.13.1/opsi_1.13.1_linux_amd64.tar.gz"
        sha256 "fadd61aab7d06cb0a7b69e0d0809e9121540f6ff0e34391f4e2283b107705cfa"

        def install
          bin.install "opsi"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/beliven-it/opsi/releases/download/1.13.1/opsi_1.13.1_linux_arm64.tar.gz"
        sha256 "975eb789238d6c4c400a127cde9aa45605d7aed1d7036d7705ec9b091979a2da"

        def install
          bin.install "opsi"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Run `opsi init` to generate config file inside
       `~/.config/opsi/config.yml` (works only if not exists yet).

       Type `opsi help` for further information.
    EOS
  end
end
