# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tssh < Formula
  desc "A CLI to easily sync, list, search and connect to Goleport nodes"
  homepage ""
  version "1.2.0"
  license "MIT"

  depends_on "fzf"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/beliven-it/tssh/releases/download/v1.2.0/tssh_1.2.0_darwin_amd64.tar.gz"
      sha256 "2626224fa179f5b12c2db2c74dfcbe369a388d26982f6ac5ffb27aeedf5b770d"

      def install
        bin.install "tssh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/beliven-it/tssh/releases/download/v1.2.0/tssh_1.2.0_darwin_arm64.tar.gz"
      sha256 "e237a087ca58e35e7c0df070ccf7a8fc4912fab60fd58b15541c6c0ed06139db"

      def install
        bin.install "tssh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/beliven-it/tssh/releases/download/v1.2.0/tssh_1.2.0_linux_amd64.tar.gz"
      sha256 "a4cb6191a7bba9dfca9fceda4bbdd9ba0e8ae3bfaba8bc8e26fcd3e6bfefc393"

      def install
        bin.install "tssh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/beliven-it/tssh/releases/download/v1.2.0/tssh_1.2.0_linux_arm64.tar.gz"
      sha256 "7fe7f618eb72fffaa40427ead14ff43913ccdce8446114e3f6870274e2effbc1"

      def install
        bin.install "tssh"
      end
    end
  end

  def caveats
    <<~EOS
      Run `tssh init` to generate config file inside
       `~/.config/tssh/config.yml` (works only if not exists yet)
       or let the CLI creating it automatically on first run (every command).

       Type `tssh help` for further information.
    EOS
  end
end
