# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tssh < Formula
  desc "A CLI to easily sync, list, search and connect to Goleport nodes"
  homepage ""
  version "1.1.0-rc"
  license "MIT"

  depends_on "fzf"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/beliven-it/tssh/releases/download/v1.1.0-rc/tssh_1.1.0-rc_darwin_arm64.tar.gz"
      sha256 "91ebb5f3473bd9432f6c669910becf5155a4979dbe8e77f5ee54d22462cc667e"

      def install
        bin.install "tssh"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/beliven-it/tssh/releases/download/v1.1.0-rc/tssh_1.1.0-rc_darwin_amd64.tar.gz"
      sha256 "e640e41c008602d92b3564091825aa3c0985cfb74dcd490e32b4ffb8925b1d90"

      def install
        bin.install "tssh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/beliven-it/tssh/releases/download/v1.1.0-rc/tssh_1.1.0-rc_linux_amd64.tar.gz"
      sha256 "ac721079edbc05281e186124a158508033a3e6f2598007553aa0f94c35007ddd"

      def install
        bin.install "tssh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/beliven-it/tssh/releases/download/v1.1.0-rc/tssh_1.1.0-rc_linux_arm64.tar.gz"
      sha256 "8acec5ec3bdbbdd3507f57747a47b6c1b26b01314bbad20cefad2ad7cd8dc360"

      def install
        bin.install "tssh"
      end
    end
  end

  def caveats
    <<~EOS
      Run `tssh init` to generate config file inside
       `~/.config/tssh/config.yml` (works only if not exists yet)
       or let the CLI creating it automatically on first run (every command).

       Type `tssh help` for further information.
    EOS
  end
end
