# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TsshAT131 < Formula
  desc "A CLI to easily list, search and connect to Goleport nodes"
  homepage ""
  version "1.3.1"
  license "MIT"

  depends_on "fzf"
  depends_on "teleport"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/beliven-it/tssh/releases/download/v1.3.1/tssh_1.3.1_darwin_amd64.tar.gz"
      sha256 "1cdc26ac0a39bc86bfacebc37eef9a6f02b0f358b379ef7b618463c145318d55"

      def install
        bin.install "tssh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/beliven-it/tssh/releases/download/v1.3.1/tssh_1.3.1_darwin_arm64.tar.gz"
      sha256 "c5df42986c079606272e7d77b9d9ba21702a32d6ba33133900bb7efabe4fcd09"

      def install
        bin.install "tssh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/beliven-it/tssh/releases/download/v1.3.1/tssh_1.3.1_linux_amd64.tar.gz"
      sha256 "707837f128f12e49886ceaf127d757473868f99668e0fad16c8585a767d53580"

      def install
        bin.install "tssh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/beliven-it/tssh/releases/download/v1.3.1/tssh_1.3.1_linux_arm64.tar.gz"
      sha256 "770408e1c6a9beecb7abbe19386c056a7258e524576e4ce0d303139962991a40"

      def install
        bin.install "tssh"
      end
    end
  end

  def caveats
    <<~EOS
      Run `tssh init` to generate config file inside
       `~/.config/tssh/config.yml` (works only if not exists yet)
       or let the CLI creating it automatically on first run (every command).

       Type `tssh help` for further information.
    EOS
  end
end
